allowBuilds:
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@react-pdf/font@4.0.11'
  - '@react-pdf/image@3.1.2'
  - '@react-pdf/layout@5.0.0'
  - '@react-pdf/paginate@1.0.0'
  - '@react-pdf/primitives@4.4.0'
  - '@react-pdf/render@4.6.2'
  - '@react-pdf/renderer@4.7.0'
  - '@react-pdf/stylesheet@6.2.4'
  - '@react-pdf/svg@1.1.1'
  - '@react-pdf/textkit@6.4.2'
  - '@react-pdf/types@2.12.0'
